version: '3'
services:
  #=============================================================================================================
  # PROMETHEUS
  #
  # O console web pode ser acessado através da URL http://localhost:9090/.
  #
  # Referência:
  # - https://hub.docker.com/r/prom/prometheus
  # - https://prometheus.io/docs/introduction/overview/
  # - https://prometheus.io/docs/prometheus/latest/storage/
  # - https://prometheus.io/docs/prometheus/latest/feature_flags/
  # - https://prometheus.io/docs/prometheus/latest/configuration/template_reference/
  #=============================================================================================================
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command: [
      "--config.file=/etc/prometheus/prometheus.yml",
      "--enable-feature=exemplar-storage",
      "--storage.tsdb.path=/prometheus",
      "--web.console.libraries=/usr/share/prometheus/console_libraries",
      "--web.console.templates=/usr/share/prometheus/consoles",
      "--web.enable-remote-write-receiver"
    ]
  #=============================================================================================================
  # GRAFANA
  #
  # Referência:
  # - https://grafana.com/docs/grafana/latest/getting-started/
  # - https://grafana.com/docs/grafana/latest/setup-grafana/
  # - https://hub.docker.com/r/grafana/grafana-oss
  # - https://github.com/grafana/grafana
  #=============================================================================================================
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_USERS_DEFAULT_THEME=dark
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  prometheus_data:
    driver: local
  grafana_data:
    driver: local